### ISSUE TITLE
[BUG] Magento 2.3.3 prefetch cache issue

### ISSUE THREAD

**Issue by congson95dev** [rafaelstz/magento2-quicklink#8]
Hi, i've install your module and found there is an issue in Magento 2.3.3:

First, i hover on the parent of jacket-women.html, and it load the prefetch cache as expected.
But when i click on jacket-women.html, the page still using normal load instead of prefetch cache.

![Magento 2 Quicklink](http://i.imgur.com/gBlMiZb.png)

Can you provide me a solution to fix this? Thanks.

**Comment by rafaelstz** [comment]
Hi @saxsax1995, this is happening because of the cache header, in your local environment without Varnish and HTTP2 you will see a small improvement in your TTFB, but to see the **prefetch cache** you should have HTTP2 and a good cache setup in your server.
To test in any Magento 2 project even not installing the module you can run this code below in your browser console.

```
require(['jquery', 'https://cdnjs.cloudflare.com/ajax/libs/quicklink/2.0.0/quicklink.umd.js', 'https://polyfill.io/v3/polyfill.min.js?features=IntersectionObserver', 'domReady!'], function($, quicklink) {
        quicklink.listen({
            timeout: 500,priority: 100,throttle: 5,priority: 0,ignores: [
                /\/api\/?/,
                uri => uri.includes('#'),
                uri => uri.includes('logout'),
                uri => uri.includes('account'),
                uri => uri.includes('checkout'),
                (uri, elem) => elem.hasAttribute('noprefetch')
            ]
        });
    });
```

After a wait for the pre-fetching and accessing any link you will see should see these reports.

![Capture d’écran, le 2021-01-04 à 16 06 18](https://user-images.githubusercontent.com/610598/103584978-5019a280-4eb0-11eb-9414-cbc260c6e4fd.png)
![Capture d’écran, le 2021-01-04 à 16 14 17](https://user-images.githubusercontent.com/610598/103584984-51e36600-4eb0-11eb-930e-efd085dbf27f.png)
